### ISSUE TITLE
w5500 causing boot looping

### ISSUE THREAD

**Issue by luw** [sonocotta/raspberry-media-center#1]
Hello 2 issues regarding networking and hoping you can help me out.

using RPi Zero 2 W, OS DietPi v9.4.2 (armv7l)  [config.txt](https://github.com/sonocotta/raspberry-media-center/files/15366651/config.txt)

1. system wont boot (loops) unless the network cable is unplugged
2. once system boots unplugged, the MAC is unique every time.

Here is the serial dump, at the end it will just reboot to "[0.00000] Booting Linux..."
[bootlooping_log.txt](https://github.com/sonocotta/raspberry-media-center/files/15366658/bootlooping_log.txt)

If I disconnect the cable, then power on, the board seems to boot correctly.  At this point if cable is connected, the interface seems to operate fine.  Only, the MAC address changes upon every reboot.

**Comment by anabolyc** [comment]
Hey @luw 

Quick check, are you using USB-PD enabled power adapter? You should be able to measure more than 5V on the VUSB test point, since otherwise board will not be able to supply 5V to the Pi.

![image](https://github.com/sonocotta/raspberry-media-center/assets/5459747/51a9080a-95d6-4d80-a7f0-293cf2300a82)


As for the MAC change, I'm not an expert on DietPi, but I remember the same feature on the Armbian, that was advertised as some security feature (rubbish). Can you please double check if you get the same behavior with Raspbian?

**Comment by luw** [comment]
Excellent thought, I was using regular USB, it tested 4.9v, must have been browning out.   I've switched to a PD, it measures 20v supply and can boot with the cable connected.  issue fixed thank you

For the MAC, could very well be a sw (OS) issue.  I will research this some more and report back.

**Comment by luw** [comment]
hello again, this is definitely a configuration issue.  Thank you again for your help, this is a great product.

**Comment by anabolyc** [comment]
Hey @luw if you managed to fix it, please let me know how to do it

**Comment by luw** [comment]
Hi @anabolyc I'm sorry I missed this before.  It seems there are other ways to do it but the "handle it in DTB" worked for me.  It's a manual hack that requires the user to manually enter the MACs for each devices, but it works.

1. Downloaded the w5500 [overlay file](https://raw.githubusercontent.com/raspberrypi/linux/rpi-6.6.y/arch/arm/boot/dts/overlays/w5500-overlay.dts)
2. uncomment this line and change the MAC to your liking `//				local-mac-address = [aa bb cc dd ee ff];`
3. saved the file as `w5500-overlay-custom.dts`
4. create the binary with the following: `dtc -I dts -O dtb -o w5500-custom.dtbo w5500-overlay-custom.dts`
5. backup the original w5500.dtbo: `sudo mv /boot/overlays/w5500.dtbo /boot/overlays/w5500.dtboBACKUP`
6. move the new .dtbo into the overlays directory: `sudo cp w5500-custom.dtbo /boot/overlays/w5500.dtbo`
7. reboot and `ip a` will report the new MAC address

My system is the following
HW: RPi Zero 2 W
OS: DietPi v9.4.2 (armv7l)
kernel: Linux 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux


sources: 
https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/device-tree.adoc
https://www.raspberrypi.com/documentation/computers/configuration.html#device-trees-overlays-and-parameters
among others...

**Comment by anabolyc** [comment]
Thanks @luw , just addded to docs.
